version: "3.8"

services:
  compiler_api:
    build: 
      context: ./api
    container_name: compiler_api
    restart: always
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - ./data/compiler/packages:/compiler/packages
    tmpfs:
      - /tmp:exec
    environment:
      - COMPILER_RUN_TIMEOUT=10000
      - COMPILER_RUN_CPU_TIME=10000
      - COMPILER_COMPILE_TIMEOUT=20000
